networks:
  card-network:
    driver: bridge

services:
  card-frontend:
    build: .
    image: card-frontend:v1
    ports:
      - 4200:4200
    environment:
      API_BASE_URL: "http://localhost:8080"
    networks:
      - card-network
